"""
SERP-like image-grid helper.

Builds a numpy RGB array where:
  - N_rows × N_cols image cells are arranged in a grid
  - Each cell is a small pixel mosaic generated by a user-supplied palette func
  - Cells are separated by white gutter pixels (preserving the SERP-look)
"""

from __future__ import annotations

import numpy as np


def build_serp_grid(palette_func, n_cell_rows: int, n_cell_cols: int,
                    px_per_cell_row: int = 6, px_per_cell_col: int = 6,
                    gutter_px: int = 2, seed_base: int = 42):
    """Return an (H, W, 3) RGB array in 0..1.

    palette_func(n, seed) -> array-like of n RGB triplets in 0..1.
    """
    H = n_cell_rows * px_per_cell_row + (n_cell_rows + 1) * gutter_px
    W = n_cell_cols * px_per_cell_col + (n_cell_cols + 1) * gutter_px
    arr = np.ones((H, W, 3))

    for cr in range(n_cell_rows):
        for cc in range(n_cell_cols):
            seed_local = seed_base + cr * 1000 + cc
            n_px = px_per_cell_row * px_per_cell_col
            pal = np.asarray(palette_func(n_px, seed=seed_local))
            top0 = (cr + 1) * gutter_px + cr * px_per_cell_row
            left0 = (cc + 1) * gutter_px + cc * px_per_cell_col
            for k in range(n_px):
                pi, pj = divmod(k, px_per_cell_col)
                arr[top0 + pi, left0 + pj] = pal[k]
    return arr
